version: '3.7'

services:
  MLWEB_WBSITE:
    build: ./WebSite
    image: docker-flask-torch-website
    ports: 
      - 1234:1234

  MLWEB_KERNEL:
    build: ./MLKernel
    image: docker-flask-torch-mlkernel
    ports: 
      - 5678:5678