version: '3.7'

services:

  MLWEB_FRONTEND:
    image: docker-flask-torch-frontend
    ports: 
      - 8080:1234

  
  MLWEB_BACKEND:
    image: docker-flask-torch-backend
    ports: 
      - 5678:5678