apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: mlweb-website
  name: mlweb-website
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mlweb-website
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/mlweb-docker-default: "true"
        io.kompose.service: mlweb-website
    spec:
      containers:
        - image: docker-flask-torch-website
          imagePullPolicy: IfNotPresent
          name: mlweb-website
          ports:
            - containerPort: 1234
              hostPort: 1234
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
