apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: 105552010/k8s-demo:v1
            args:
            - /bin/sh
            - -c
            - date; echo Hello
          restartPolicy: OnFailure